name: Backend Monitoring Server Deploy

on:
  push:
    branches: [ "init-setting" ]
    paths:
      - 'config/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test

#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          token: ${{ secrets.ACTION_TOKEN }}
#          submodules: true
#
#      - name: Run Docker Containers
#        working-directory: ./config
#        run: docker-compose -f docker-compose.yml up -d
